alias ff='~/tools/firefox/firefox-bin &> /dev/null &'
alias g='git'
alias idea='idea.sh &> /dev/null &'
alias l='ls'
alias ls='ls -l --color=auto'
alias pycharm='pycharm.sh &> /dev/null &'
alias t='tmux'
alias tkill='tmux kill-server'
alias tls='tmux ls'
alias vi='vim' 
alias view='vim -R' 
