alias ff='~/tools/firefox/firefox-bin &> /dev/null &'
alias g='git'
alias idea='idea.sh &'
alias ls='ls -l --color=auto'
alias pycharm='pycharm.sh &> /dev/null &'
alias t='tmux'
alias vi='vim' 
alias view='vim -R' 
