---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Say hello
    debug: msg="Hello world!"

  - name: Update apt cache
    apt:
      update_cache: yes
    become: true

  - name: Install vim
    apt:
      name: vim
      state: present
    become: true

  - name: Install tmux
    apt:
      name: tmux
      state: present
    become: true

  - name: Install python-pip
    apt:
      name: python-pip
      state: present
    become: true

  - name: Install xclip
    apt:
      name: xclip
      state: present
    become: true

  - name: Install JDK8
    apt:
      name: openjdk-8-jdk
      state: present
    become: true

  - name: Set home directory 
    set_fact: 
      home_dir: "/home/parallels"

  - name: Set facts
    set_fact:
      dev_setup_dir: "{{ home_dir }}/dev/dev-setup"
      download_dir: "{{ home_dir }}/Downloads"
      tools_dir: "{{ home_dir }}/tools" 
      idea_archive: "ideaIC-2017.1-no-jdk.tar.gz"
      pycharm_archive: "pycharm-community-2017.1.tar.gz"

  - name: Create tools dir 
    file: 
      path: "{{ tools_dir }}" 
      state: directory

  - name: Delete IDEA tarball 
    file: 
      path: "{{ download_dir }}/{{ idea_archive }}" 
      state: absent

  - name: Download IDEA tarball 
    get_url: 
      url: "https://download.jetbrains.com/idea/{{ idea_archive }}" 
      dest: "{{ download_dir }}/{{ idea_archive }}"

    # TODO Unarchive IDEA
  - name: Unarchive IDEA
    debug: msg="Unarchiving IDEA" 

  - name: Delete PyCharm tarball 
    file: 
      path: "{{ download_dir }}/{{ pycharm_archive }}" 
      state: absent

  - name: Download PyCharm tarbll 
    get_url: 
      url: "https://download.jetbrains.com/python/{{ pycharm_archive }}" 
      dest: "{{ download_dir }}/{{ pycharm_archive }}"

    # TODO Unarchive PyCharm
  - name: Unarchive PyCharm 
    debug: msg="Unarchiving PyCharm"

  - name: Create symlinks
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { src: "{{ dev_setup_dir }}/profile", dest: "{{ home_dir }}/.profile" }
      - { src: "{{ dev_setup_dir }}/bashrc", dest: "{{ home_dir}}/.bashrc" }
      - { src: "{{ dev_setup_dir }}/bash_aliases", dest: "{{ home_dir }}/.bash_aliases" }
      - { src: "{{ dev_setup_dir }}/tmux.conf", dest: "{{ home_dir }}/.tmux.conf" }
      - { src: "{{ dev_setup_dir }}/vimrc", dest: "{{ home_dir }}/.vimrc" }
      - { src: "{{ tools_dir }}/idea-IC-171.3780.107", dest: "{{ tools_dir }}/idea" } 
      - { src: "{{ tools_dir }}/pycharm-community-2017.1", dest: "{{ tools_dir }}/pycharm" }

