---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
    become: True

  - name: Install tools from apt
    apt:
      name: "{{ item }}"
      state: present
    with_items: 
    - vim 
    - tmux 
    - python-pip 
    - xclip 
    - openjdk-8-jdk
    - htop
    become: True
  
  - name: Set home directory 
    set_fact: 
      home_dir: "/home/parallels"

  - name: Set facts 1
    set_fact:
      dev_setup_dir: "{{ home_dir }}/dev/dev-setup"
      download_dir: "{{ home_dir }}/Downloads"
      tools_dir: "{{ home_dir }}/tools" 
      idea_archive: "ideaIC-2017.1-no-jdk.tar.gz"
      pycharm_archive: "pycharm-community-2017.1.tar.gz"

  - name: Set facts 2
    set_fact: 
      idea_dir: "{{ tools_dir }}/idea-IC-171.3780.107"
      pycharm_dir: "{{ tools_dir }}/pycharm-community-2017.1"

  - name: Create tools dir 
    file: 
      path: "{{ tools_dir }}" 
      state: directory

  - name: Delete IDEA tarball 
    file: 
      path: "{{ download_dir }}/{{ idea_archive }}" 
      state: absent

  - name: Delete IDEA dir 
    file: 
      path: "{{ idea_dir }}"
      state: absent

  - name: Download IDEA tarball 
    get_url: 
      url: "https://download.jetbrains.com/idea/{{ idea_archive }}" 
      dest: "{{ download_dir }}/{{ idea_archive }}"

  - name: Unarchive IDEA
    unarchive: 
      src: "{{ download_dir }}/{{ idea_archive }}" 
      dest: "{{ tools_dir }}"
      remote_src: True

  - name: Delete PyCharm tarball 
    file: 
      path: "{{ download_dir }}/{{ pycharm_archive }}" 
      state: absent

  - name: Delete PyCharm dir 
    file: 
      path: "{{ pycharm_dir }}" 
      state: absent

  - name: Download PyCharm tarball 
    get_url: 
      url: "https://download.jetbrains.com/python/{{ pycharm_archive }}" 
      dest: "{{ download_dir }}/{{ pycharm_archive }}"

  - name: Unarchive PyCharm 
    unarchive: 
      src: "{{ download_dir }}/{{ pycharm_archive }}" 
      dest: "{{ tools_dir }}"
      remote_src: True

  - name: Create symlinks
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { src: "{{ dev_setup_dir }}/profile", dest: "{{ home_dir }}/.profile" }
      - { src: "{{ dev_setup_dir }}/bashrc", dest: "{{ home_dir}}/.bashrc" }
      - { src: "{{ dev_setup_dir }}/bash_aliases", dest: "{{ home_dir }}/.bash_aliases" }
      - { src: "{{ dev_setup_dir }}/tmux.conf", dest: "{{ home_dir }}/.tmux.conf" }
      - { src: "{{ dev_setup_dir }}/vimrc", dest: "{{ home_dir }}/.vimrc" }
      - { src: "{{ tools_dir }}/idea-IC-171.3780.107", dest: "{{ tools_dir }}/idea" } 
      - { src: "{{ tools_dir }}/pycharm-community-2017.1", dest: "{{ tools_dir }}/pycharm" }

  - name: Install powerline from pip
    command: "pip install --user git+git://github.com/Lokaltog/powerline"

  - name: Download fonts
    get_url:
      url: "{{ item }}"
      dest: "{{ download_dir }}/"
    with_items:
    - "https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf"
    - "https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf"

  - name: Move PowerlineSymbols.otf
    command: "mv {{ download_dir }}/PowerlineSymbols.otf /usr/share/fonts/"
    become: True

  - name: Reload font cache
    command: "fc-cache"
    become: True

  - name: Move 10-powerline-symbols.conf
    command: "mv {{ download_dir }}/10-powerline-symbols.conf /etc/fonts/conf.d/"
    become: True
~
