---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Say hello
    debug: msg="Hello world!"

  - name: Update apt cache
    apt:
      update_cache: yes
    become: true

  - name: Install vim
    apt:
      name: vim
      state: present
    become: true

  - name: Install tmux
    apt:
      name: tmux
      state: present
    become: true

  - name: Install python-pip
    apt:
      name: python-pip
      state: present
    become: true

  - name: Install xclip
    apt:
      name: xclip
      state: present
    become: true

  - name: Install JDK8
    apt:
      name: openjdk-8-jdk
      state: present
    become: true

  - name: Set facts
    set_fact:
      home_dir: /home/parallels
      dev_setup_dir: /home/parallels/dev/dev-setup

  - name: Create symlinks
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { src: "{{ dev_setup_dir }}/profile", dest: "{{ home_dir }}/.profile" }
      - { src: "{{ dev_setup_dir }}/bashrc", dest: "{{ home_dir}}/.bashrc" }
      - { src: "{{ dev_setup_dir }}/bash_aliases", dest: "{{ home_dir }}/.bash_aliases" }
      - { src: "{{ dev_setup_dir }}/tmux.conf", dest: "{{ home_dir }}/.tmux.conf" }
      - { src: "{{ dev_setup_dir }}/vimrc", dest: "{{ home_dir }}/.vimrc" }